using System.Text.Json.Serialization;

namespace AiIncubator.Server.Models.Glm;

/// <summary>
/// Function call details within a <see cref="GlmToolCall"/>.
/// </summary>
public class GlmFunctionCall
{
    /// <summary>Model-generated function name to invoke.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>JSON-formatted string of function call parameters generated by the model.</summary>
    [JsonPropertyName("arguments")]
    public string Arguments { get; set; } = "{}";
}
