using System.Text.Json.Serialization;

namespace AiIncubator.Server.Models.Glm;

/// <summary>
/// Represents a single message in the ZhipuAI GLM conversation.
/// Used for all message roles: system, user, assistant, and tool.
/// </summary>
public class GlmMessage
{
    /// <summary>
    /// Role of the message author.
    /// Valid values: <c>"system"</c>, <c>"user"</c>, <c>"assistant"</c>, <c>"tool"</c>.
    /// </summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;

    /// <summary>
    /// Message text content. For assistant messages with tool calls, this is typically <c>null</c>.
    /// </summary>
    [JsonPropertyName("content")]
    public string? Content { get; set; }

    /// <summary>
    /// Reasoning content produced by the model's chain-of-thought when thinking mode is enabled.
    /// </summary>
    [JsonPropertyName("reasoning_content")]
    public string? ReasoningContent { get; set; }

    /// <summary>
    /// Tool call messages generated by the model.
    /// When this field is populated, <see cref="Content"/> is usually <c>null</c>.
    /// </summary>
    [JsonPropertyName("tool_calls")]
    public List<GlmToolCall>? ToolCalls { get; set; }

    /// <summary>
    /// Indicates the tool call ID corresponding to this message.
    /// Required for messages with <see cref="Role"/> = <c>"tool"</c>.
    /// </summary>
    [JsonPropertyName("tool_call_id")]
    public string? ToolCallId { get; set; }
}
