using System.Text.Json.Serialization;

namespace AiIncubator.Server.Models.Glm;

/// <summary>
/// Represents a tool call generated by the model in the assistant response.
/// </summary>
public class GlmToolCall
{
    /// <summary>Unique identifier for the tool call.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Tool type called by the model. Values: <c>"function"</c>, <c>"web_search"</c>, <c>"retrieval"</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = "function";

    /// <summary>The function call details including name and arguments.</summary>
    [JsonPropertyName("function")]
    public GlmFunctionCall Function { get; set; } = new();
}
